FROM python:3.12-slim AS base
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /pyspur/backend
COPY backend/requirements.txt .
RUN pip install -r requirements.txt

# Development stage
FROM base AS development
ENV PYTHONPATH=/pyspur/backend
# Development-specific instructions here

# Production stage
FROM base AS production
ENV PYTHONPATH=/pyspur/backend
COPY backend/ .
# Production-specific instructions here 