"""pause_model

Revision ID: 007
Revises: 006
Create Date: 2025-02-22 04:58:12.299496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pause_history',
    sa.Column('_intid', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), sa.Computed("'PH' || _intid", ), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('pause_message', sa.String(), nullable=True),
    sa.Column('pause_time', sa.DateTime(), nullable=False),
    sa.Column('resume_time', sa.DateTime(), nullable=True),
    sa.Column('resume_user_id', sa.String(), nullable=True),
    sa.Column('resume_action', sa.Enum('APPROVE', 'DECLINE', 'OVERRIDE', name='pauseaction'), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('_intid'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pause_history')
    # ### end Alembic commands ###
