"""add_slack_tokens

Revision ID: 012
Revises: 011
Create Date: 2025-03-18 18:10:53.774095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012'
down_revision: Union[str, None] = '011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_agents', sa.Column('has_bot_token', sa.Boolean(), nullable=True))
    op.add_column('slack_agents', sa.Column('has_user_token', sa.Boolean(), nullable=True))
    op.add_column('slack_agents', sa.Column('last_token_update', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_agents', 'last_token_update')
    op.drop_column('slack_agents', 'has_user_token')
    op.drop_column('slack_agents', 'has_bot_token')
    # ### end Alembic commands ###
