"""add_date_to_slack_agent

Revision ID: 013
Revises: 012
Create Date: 2025-03-18 18:27:04.191108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013'
down_revision: Union[str, None] = '012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_agents', sa.Column('spur_type', sa.String(), nullable=True))
    op.add_column('slack_agents', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_agents', 'created_at')
    op.drop_column('slack_agents', 'spur_type')
    # ### end Alembic commands ###
