"""add_persistent_socket_mode

Revision ID: 015
Revises: 014
Create Date: 2025-03-22 11:32:40.009239

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "015"
down_revision: Union[str, None] = "014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slack_agents",
        sa.Column("socket_mode_enabled", sa.Boolean(), nullable=True, server_default="false"),
    )

    # Set default value for existing records
    op.execute(
        "UPDATE slack_agents SET socket_mode_enabled = false WHERE socket_mode_enabled IS NULL"
    )

    # Make the column not nullable after setting default values
    op.alter_column("slack_agents", "socket_mode_enabled", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slack_agents", "socket_mode_enabled")
    # ### end Alembic commands ###
